///////////////////////////////////////////////////////////////////////////////
// Unbenannt1ClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "Unbenannt1ClassFactory.h"
#include "Unbenannt1Services.h"
#include "Unbenannt1Version.h"
#include "Module1.h"

BEGIN_CLASS_MAP(CUnbenannt1ClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_Unbenannt1CModule1, SRVNAME_UNBENANNT1 "!CModule1", CModule1)
///</AutoGeneratedContent>
END_CLASS_MAP()

CUnbenannt1ClassFactory::CUnbenannt1ClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_UNBENANNT1)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(Unbenannt1));
#endif //defined(TCDBG_UNIT_VERSION)
}

