///////////////////////////////////////////////////////////////////////////////
// Unbenannt1Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Unbenannt1 = 0x3F000000;
#define SRVNAME_UNBENANNT1 "Unbenannt1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Unbenannt1CModule1 = {0xf6e1decc,0x7ec5,0x4981,{0x8a,0xc7,0x8a,0xb2,0x03,0xe7,0xb9,0x72}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1Parameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Parameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} Module1Parameter, *PModule1Parameter;

typedef struct _Module1Inputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
	BOOL Rst;
} Module1Inputs, *PModule1Inputs;

typedef struct _Module1Outputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} Module1Outputs, *PModule1Outputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
